### ISSUE TITLE
Error on setEndingPosition

### ISSUE THREAD

**Issue by Cryptite** [MeRPG/GuardianBeamAPI#1]
Unsure what's up, but get this error whenever updating the ending position on a Beam object: https://hastebin.com/befufosuco.swift

ProtocolLib is b390 atm, also running PaperSpigot

**Comment by MeRPG** [comment]
Hey, sorry about that. I should probably make it more clear on the github that this project is abandoned. Anybody wishing to continue work on this library is free to do so, so long as they comply with the terms of the MIT license.
