### ISSUE TITLE
Jar file

### ISSUE THREAD

**Issue by SamB440** [MeRPG/GuardianBeamAPI#2]
Greetings,

I see you updated to 1.12, but did not provide a jar file. You should definitely consider doing this, as I had to compile this entirely myself :/

**Comment by MeRPG** [comment]
Hey, sorry about that. I should probably make it more clear on the github that this project is abandoned. Anybody wishing to compile 1.12 themselves or distribute compiled versions of this library is free to do so, so long as they comply with the terms of the MIT license.
